import { useState } from 'react'
import { Plus, Check, X, Car, Play, Flag, Pencil, Trash2 } from 'lucide-react'
import { useStore, useCurrentUser } from '@/store/useStore'
import { Card, PageHeader, Stat, Modal, Field, Alert, Tabs } from '@/components/ui'
import { TRIP_STATUS_LABEL, TRIP_STATUS_TONE, VEHICLE_STATUS_LABEL, canDecideTwoStep, availableVehicles } from '@/lib/supply'
import { fmtMoney, fmtDate, cx } from '@/lib/format'
import { useSupplyContext, TwoStepTrail } from './shared'
import type { TripRequest, TripPassenger, Vehicle } from '@/types'

export default function Fleet() {
  const user = useCurrentUser()!
  const { supplyManage } = useSupplyContext()
  const { trips, vehicles, staff, projects, budgets, settings, country, createTrip, decideTrip, assignTrip, startTrip, closeTrip, upsertVehicle } = useStore()
  const me = staff.find((s) => s.userId === user.id)
  const [tab, setTab] = useState<'trips' | 'vehicles'>('trips')
  const [filter, setFilter] = useState<'open' | 'mine' | 'all'>('open')
  const [nw, setNw] = useState<{ passengerType: 'staff' | 'beneficiary'; passengers: TripPassenger[]; from: string; to: string; date: string; time: string; returnDate: string; purpose: string; projectId: string; budgetLine: string } | null>(null)
  const [decide, setDecide] = useState<{ t: TripRequest; approve: boolean } | null>(null)
  const [note, setNote] = useState('')
  const [assign, setAssign] = useState<{ t: TripRequest; vehicleId: string; driverName: string } | null>(null)
  const [start, setStart] = useState<{ t: TripRequest; odo: number } | null>(null)
  const [close, setClose] = useState<{ t: TripRequest; endOdometer: number; cost: number; costNote: string } | null>(null)
  const [veh, setVeh] = useState<Partial<Vehicle> | null>(null)
  const [msg, setMsg] = useState<{ tone: 'success' | 'danger'; text: string } | null>(null)
  const list = trips.filter((t) => filter === 'all' || (filter === 'mine' ? t.requesterId === user.id : !['closed', 'rejected', 'cancelled'].includes(t.status))).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
  const forMe = trips.filter((t) => t.status === 'pending_approval' && canDecideTwoStep(t.approvals, user) && t.requesterId !== user.id)
  const budgetLines = (projectId: string) => { const p = projects.find((x) => x.id === projectId); return budgets.find((x) => x.id === p?.budgetId)?.lines ?? [] }
  const monthCost = trips.filter((t) => t.status === 'closed' && t.closedAt?.startsWith(new Date().toISOString().slice(0, 7))).reduce((s, t) => s + (t.cost ?? 0), 0)
  const vList = vehicles.filter((v) => country === 'all' || v.country === country)
  return (
    <>
      <PageHeader title="Fleet & transport" subtitle="Transport requests for staff or beneficiaries — who (RHS number), from where to where, for which project — approved by the line manager then Supply Chain; a vehicle and driver are assigned; the trip is closed with its cost, which lands on the project's BvA."
        actions={<div className="flex gap-2">{supplyManage && tab === 'vehicles' && <button className="btn-primary" onClick={() => setVeh({ country: settings.countries[0], status: 'available', odometer: 0, year: new Date().getFullYear() })}><Plus size={15} /> Vehicle</button>}<button className="btn-primary" data-testid="new-trip" onClick={() => setNw({ passengerType: 'staff', passengers: me ? [{ name: me.name, rhsNumber: me.rhsNumber }] : [], from: '', to: '', date: '', time: '08:00', returnDate: '', purpose: '', projectId: '', budgetLine: '' })}><Plus size={15} /> Transport request</button></div>} />
      <div className="mb-5 grid gap-4 sm:grid-cols-5"><Stat label="Awaiting your approval" value={forMe.length} tone={forMe.length ? 'sun' : 'default'} /><Stat label="To assign a vehicle" value={trips.filter((t) => t.status === 'approved').length} /><Stat label="On the road" value={trips.filter((t) => t.status === 'in_progress').length} tone="brand" /><Stat label="Vehicles available" value={`${availableVehicles(vList).length} / ${vList.length}`} /><Stat label="Transport cost this month" value={fmtMoney(monthCost, settings.defaultCurrency)} hint="charged to projects (BvA)" /></div>
      {msg && <div className="mb-4"><Alert tone={msg.tone}>{msg.text}</Alert></div>}
      <Tabs tabs={[{ id: 'trips', label: 'Transport requests', count: list.length }, { id: 'vehicles', label: 'Vehicles', count: vList.length }]} value={tab} onChange={setTab} />
      {tab === 'trips' && <>
        <div className="my-3 flex gap-1">{(['open', 'mine', 'all'] as const).map((f) => <button key={f} onClick={() => setFilter(f)} className={cx('rounded-pill px-3 py-1 text-[12.5px] font-medium', filter === f ? 'bg-ink-900 text-white' : 'bg-surface text-ink-600 ring-1 ring-inset ring-line')}>{f === 'open' ? 'Open' : f === 'mine' ? 'My requests' : 'All'}</button>)}</div>
        <Card padded={false}><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-[13px]"><thead><tr><th className="table-th">Request</th><th className="table-th">Requester</th><th className="table-th">Passengers</th><th className="table-th">Route · date</th><th className="table-th">Project · line</th><th className="table-th">Approvals</th><th className="table-th">Vehicle</th><th className="table-th">Status</th><th className="table-th w-40" /></tr></thead>
          <tbody>{list.length === 0 && <tr><td colSpan={9} className="table-td text-ink-500">Nothing here.</td></tr>}{list.map((t) => <tr key={t.id} className="hover:bg-surface-muted"><td className="table-td"><span className="font-mono text-[12px]">{t.number}</span><div className="text-[12px] text-ink-600">{t.purpose}</div></td><td className="table-td"><div className="font-medium text-ink-900">{t.requesterName}</div><div className="font-mono text-[11.5px] text-ink-500">{t.rhsNumber}</div></td><td className="table-td text-[12.5px]"><span className={cx('rounded-pill px-1.5 py-0.5 text-[10.5px] font-semibold', t.passengerType === 'staff' ? 'bg-info-50 text-info-700' : 'bg-sun-100 text-sun-700')}>{t.passengerType}</span>{t.passengers.map((p, i) => <div key={i}>{p.name} <span className="font-mono text-[11px] text-ink-500">{p.rhsNumber ?? p.beneficiaryRef ?? ''}</span></div>)}</td><td className="table-td text-[12.5px]">{t.from}<div className="text-ink-500">→ {t.to}</div><div className="text-ink-500">{fmtDate(t.date)} {t.time}{t.returnDate && ` · back ${fmtDate(t.returnDate)}`}</div></td><td className="table-td text-[12.5px]">{t.projectCode ?? 'Core'}{t.budgetLine && <div className="font-mono text-[11px] text-ink-500">{t.budgetLine}</div>}</td><td className="table-td"><TwoStepTrail approvals={t.approvals} /></td><td className="table-td text-[12.5px]">{t.vehiclePlate ? <>{t.vehiclePlate}<div className="text-ink-500">{t.driverName}</div>{t.distanceKm !== undefined && <div className="text-ink-500">{t.distanceKm} km</div>}</> : '—'}</td><td className="table-td"><span className={cx('rounded-pill px-2 py-0.5 text-[11px] font-semibold', TRIP_STATUS_TONE[t.status])}>{TRIP_STATUS_LABEL[t.status]}</span>{t.status === 'closed' && <div className="text-[12px] font-semibold text-ink-900">{fmtMoney(t.cost ?? 0, t.currency)}</div>}</td>
            <td className="table-td"><div className="flex justify-end gap-1">{t.status === 'pending_approval' && canDecideTwoStep(t.approvals, user) && t.requesterId !== user.id && <><button className="btn-primary btn-sm" data-testid="trip-approve" onClick={() => { setNote(''); setDecide({ t, approve: true }) }}><Check size={13} /></button><button className="btn-danger-soft btn-sm" onClick={() => { setNote(''); setDecide({ t, approve: false }) }}><X size={13} /></button></>}{t.status === 'approved' && supplyManage && <button className="btn-primary btn-sm" data-testid="trip-assign" onClick={() => setAssign({ t, vehicleId: availableVehicles(vehicles)[0]?.id ?? '', driverName: staff.find((s) => s.id === availableVehicles(vehicles)[0]?.driverStaffId)?.name ?? '' })}><Car size={13} /> Assign</button>}{t.status === 'assigned' && supplyManage && <button className="btn-secondary btn-sm" data-testid="trip-start" onClick={() => setStart({ t, odo: vehicles.find((v) => v.id === t.vehicleId)?.odometer ?? 0 })}><Play size={13} /> Start</button>}{t.status === 'in_progress' && supplyManage && <button className="btn-primary btn-sm" data-testid="trip-close" onClick={() => setClose({ t, endOdometer: t.startOdometer ?? 0, cost: 0, costNote: '' })}><Flag size={13} /> Close</button>}</div></td></tr>)}</tbody></table></div></Card>
      </>}
      {tab === 'vehicles' && <Card className="mt-4" padded={false}><table className="w-full text-[13px]"><thead><tr><th className="table-th">Plate</th><th className="table-th">Vehicle</th><th className="table-th">Country · base</th><th className="table-th">Driver</th><th className="table-th text-right">Odometer</th><th className="table-th">Status</th><th className="table-th">Asset</th><th className="table-th w-12" /></tr></thead><tbody>{vList.map((v) => <tr key={v.id} className="hover:bg-surface-muted"><td className="table-td font-mono font-semibold">{v.plate}</td><td className="table-td">{v.makeModel} <span className="text-ink-500">{v.year}</span>{v.notes && <div className="text-[12px] text-ink-500">{v.notes}</div>}</td><td className="table-td text-[12.5px]">{v.country}</td><td className="table-td">{staff.find((s) => s.id === v.driverStaffId)?.name ?? '—'}</td><td className="table-td text-right tabular-nums">{v.odometer.toLocaleString()} km</td><td className="table-td"><span className={cx('rounded-pill px-2 py-0.5 text-[11px] font-semibold', v.status === 'available' ? 'bg-brand-100 text-brand-800' : v.status === 'on_trip' ? 'bg-brand-600 text-white' : 'bg-sun-100 text-sun-700')}>{VEHICLE_STATUS_LABEL[v.status]}</span></td><td className="table-td font-mono text-[11.5px] text-ink-500">{v.assetId ? 'on register' : '—'}</td><td className="table-td">{supplyManage && <button className="btn-ghost btn-sm" onClick={() => setVeh(v)}><Pencil size={13} /></button>}</td></tr>)}</tbody></table></Card>}

      <Modal open={!!nw} onClose={() => setNw(null)} width="max-w-3xl" title="Transport request" footer={<><button className="btn-secondary" onClick={() => setNw(null)}>Cancel</button><button className="btn-primary" data-testid="trip-submit" onClick={() => { if (!nw) return; const r = createTrip({ ...nw, returnDate: nw.returnDate || undefined, projectId: nw.projectId || undefined, projectCode: projects.find((p) => p.id === nw.projectId)?.code, budgetLine: nw.budgetLine || undefined }); if (!r.ok) return alert(r.error); setMsg({ tone: 'success', text: `${r.trip!.number} submitted for approval.` }); setNw(null) }}>Submit</button></>}>
        {nw && <div className="space-y-3 text-[13px]">
          <div className="rounded-control bg-surface-muted px-3 py-2 text-[12.5px] text-ink-700">Requested by <b>{user.name}</b> · RHS number <b className="font-mono">{me?.rhsNumber ?? '—'}</b></div>
          <div className="grid gap-3 sm:grid-cols-3"><Field label="Passengers are"><select className="input" value={nw.passengerType} onChange={(e) => setNw({ ...nw, passengerType: e.target.value as 'staff' | 'beneficiary', passengers: [] })}><option value="staff">Staff (RHS numbers)</option><option value="beneficiary">Beneficiaries</option></select></Field><Field label="From" required><input className="input" data-testid="trip-from" value={nw.from} onChange={(e) => setNw({ ...nw, from: e.target.value })} /></Field><Field label="To" required><input className="input" data-testid="trip-to" value={nw.to} onChange={(e) => setNw({ ...nw, to: e.target.value })} /></Field><Field label="Date" required><input type="date" className="input" data-testid="trip-date" value={nw.date} onChange={(e) => setNw({ ...nw, date: e.target.value })} /></Field><Field label="Time"><input type="time" className="input" value={nw.time} onChange={(e) => setNw({ ...nw, time: e.target.value })} /></Field><Field label="Return date (if round trip)"><input type="date" className="input" value={nw.returnDate} onChange={(e) => setNw({ ...nw, returnDate: e.target.value })} /></Field><Field label="Project"><select className="input" value={nw.projectId} onChange={(e) => setNw({ ...nw, projectId: e.target.value, budgetLine: '' })}><option value="">Core / none</option>{projects.filter((p) => ['granted', 'active'].includes(p.stage)).map((p) => <option key={p.id} value={p.id}>{p.code} · {p.title.slice(0, 30)}</option>)}</select></Field><Field label="Budget line (charged on closing)"><select className="input" value={nw.budgetLine} disabled={!nw.projectId} onChange={(e) => setNw({ ...nw, budgetLine: e.target.value })}><option value="">—</option>{budgetLines(nw.projectId).map((l) => <option key={l.id} value={l.code}>{l.code} · {l.description.slice(0, 30)}</option>)}</select></Field><Field label="Purpose" required><input className="input" data-testid="trip-purpose" value={nw.purpose} onChange={(e) => setNw({ ...nw, purpose: e.target.value })} /></Field></div>
          <div><div className="label">Passengers</div>{nw.passengers.map((p, i) => <div key={i} className="mb-1 grid grid-cols-[1fr_1fr_32px] gap-2"><input className="input" placeholder="Name" value={p.name} onChange={(e) => setNw({ ...nw, passengers: nw.passengers.map((x, j) => (j === i ? { ...x, name: e.target.value } : x)) })} />{nw.passengerType === 'staff' ? <select className="input font-mono" value={p.rhsNumber ?? ''} onChange={(e) => { const st = staff.find((s) => s.rhsNumber === e.target.value); setNw({ ...nw, passengers: nw.passengers.map((x, j) => (j === i ? { name: st?.name ?? x.name, rhsNumber: e.target.value } : x)) }) }}><option value="">RHS number</option>{staff.filter((s) => s.status === 'active').map((s) => <option key={s.id} value={s.rhsNumber}>{s.rhsNumber} · {s.name}</option>)}</select> : <input className="input" placeholder="Beneficiary ref. / ID" value={p.beneficiaryRef ?? ''} onChange={(e) => setNw({ ...nw, passengers: nw.passengers.map((x, j) => (j === i ? { ...x, beneficiaryRef: e.target.value } : x)) })} />}<button className="btn-ghost btn-sm text-accent-700" onClick={() => setNw({ ...nw, passengers: nw.passengers.filter((_, j) => j !== i) })}><Trash2 size={13} /></button></div>)}<button className="btn-secondary btn-sm" data-testid="trip-add-passenger" onClick={() => setNw({ ...nw, passengers: [...nw.passengers, { name: '' }] })}><Plus size={13} /> Passenger</button></div>
        </div>}
      </Modal>
      <Modal open={!!decide} onClose={() => setDecide(null)} title={decide ? `${decide.approve ? 'Approve' : 'Reject'} ${decide.t.number}` : ''} footer={<><button className="btn-secondary" onClick={() => setDecide(null)}>Cancel</button><button className={decide?.approve ? 'btn-primary' : 'btn-danger'} data-testid="trip-confirm" onClick={() => { if (decide) decideTrip(decide.t.id, decide.approve, note || undefined); setDecide(null) }}>Confirm</button></>}>
        {decide && <div className="space-y-3 text-[13px]"><p className="text-ink-700"><b>{decide.t.requesterName}</b> ({decide.t.rhsNumber}) · {decide.t.from} → {decide.t.to} · {fmtDate(decide.t.date)} {decide.t.time} · {decide.t.passengers.length} passenger(s)</p><Field label="Note (optional)"><textarea className="input min-h-[56px]" value={note} onChange={(e) => setNote(e.target.value)} /></Field></div>}
      </Modal>
      <Modal open={!!assign} onClose={() => setAssign(null)} title={assign ? `Assign vehicle — ${assign.t.number}` : ''} footer={<><button className="btn-secondary" onClick={() => setAssign(null)}>Cancel</button><button className="btn-primary" data-testid="trip-assign-confirm" onClick={() => { if (!assign?.vehicleId) return alert('Choose a vehicle.'); assignTrip(assign.t.id, assign.vehicleId, assign.driverName); setAssign(null) }}>Assign</button></>}>
        {assign && <div className="grid gap-3 sm:grid-cols-2"><Field label="Vehicle"><select className="input" value={assign.vehicleId} onChange={(e) => { const v = vehicles.find((x) => x.id === e.target.value); setAssign({ ...assign, vehicleId: e.target.value, driverName: staff.find((s) => s.id === v?.driverStaffId)?.name ?? assign.driverName }) }}><option value="">—</option>{availableVehicles(vehicles).map((v) => <option key={v.id} value={v.id}>{v.plate} · {v.makeModel} ({v.country})</option>)}</select></Field><Field label="Driver"><input className="input" value={assign.driverName} onChange={(e) => setAssign({ ...assign, driverName: e.target.value })} /></Field></div>}
      </Modal>
      <Modal open={!!start} onClose={() => setStart(null)} title={start ? `Start trip — ${start.t.number}` : ''} footer={<><button className="btn-secondary" onClick={() => setStart(null)}>Cancel</button><button className="btn-primary" data-testid="trip-start-confirm" onClick={() => { if (start) startTrip(start.t.id, start.odo); setStart(null) }}>Start</button></>}>
        {start && <Field label="Odometer at departure (km)"><input type="number" className="input" value={start.odo} onChange={(e) => setStart({ ...start, odo: Number(e.target.value) })} /></Field>}
      </Modal>
      <Modal open={!!close} onClose={() => setClose(null)} title={close ? `Close trip — ${close.t.number}` : ''} footer={<><button className="btn-secondary" onClick={() => setClose(null)}>Cancel</button><button className="btn-primary" data-testid="trip-close-confirm" onClick={() => { if (close) closeTrip(close.t.id, { endOdometer: close.endOdometer, cost: close.cost, costNote: close.costNote }); setClose(null); setMsg({ tone: 'success', text: 'Trip closed — the cost is now on the project BvA.' }) }}>Close & post cost</button></>}>
        {close && <div className="grid gap-3 sm:grid-cols-2"><Field label="Odometer at return (km)"><input type="number" className="input" data-testid="trip-end-odo" value={close.endOdometer} onChange={(e) => setClose({ ...close, endOdometer: Number(e.target.value) })} /></Field><Field label={`Cost (${close.t.currency}) — fuel, per diem, tolls`} required><input type="number" className="input" data-testid="trip-cost" value={close.cost} onChange={(e) => setClose({ ...close, cost: Number(e.target.value) })} /></Field><Field label="Cost breakdown" className="sm:col-span-2"><input className="input" value={close.costNote} onChange={(e) => setClose({ ...close, costNote: e.target.value })} placeholder="Fuel 46 + per diem 22" /></Field><div className="sm:col-span-2 text-[12.5px] text-ink-600">Distance: {Math.max(0, close.endOdometer - (close.t.startOdometer ?? 0))} km · charged to <b>{close.t.projectCode ?? 'core'} {close.t.budgetLine ?? ''}</b></div></div>}
      </Modal>
      <Modal open={!!veh} onClose={() => setVeh(null)} title={veh?.id ? `Edit ${veh.plate}` : 'Register vehicle'} footer={<><button className="btn-secondary" onClick={() => setVeh(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!veh?.plate?.trim()) return alert('Plate is required.'); upsertVehicle({ ...veh, plate: veh.plate.trim() }); setVeh(null) }}>Save</button></>}>
        {veh && <div className="grid gap-3 sm:grid-cols-2"><Field label="Plate" required><input className="input font-mono" value={veh.plate ?? ''} onChange={(e) => setVeh({ ...veh, plate: e.target.value })} /></Field><Field label="Make / model"><input className="input" value={veh.makeModel ?? ''} onChange={(e) => setVeh({ ...veh, makeModel: e.target.value })} /></Field><Field label="Year"><input type="number" className="input" value={veh.year ?? ''} onChange={(e) => setVeh({ ...veh, year: Number(e.target.value) })} /></Field><Field label="Country"><select className="input" value={veh.country} onChange={(e) => setVeh({ ...veh, country: e.target.value })}>{settings.countries.map((c) => <option key={c}>{c}</option>)}</select></Field><Field label="Default driver"><select className="input" value={veh.driverStaffId ?? ''} onChange={(e) => setVeh({ ...veh, driverStaffId: e.target.value || undefined })}><option value="">—</option>{staff.filter((s) => s.status === 'active').map((s) => <option key={s.id} value={s.id}>{s.rhsNumber} · {s.name}</option>)}</select></Field><Field label="Status"><select className="input" value={veh.status} onChange={(e) => setVeh({ ...veh, status: e.target.value as Vehicle['status'] })}>{(Object.keys(VEHICLE_STATUS_LABEL) as Vehicle['status'][]).map((s) => <option key={s} value={s}>{VEHICLE_STATUS_LABEL[s]}</option>)}</select></Field><Field label="Odometer (km)"><input type="number" className="input" value={veh.odometer ?? 0} onChange={(e) => setVeh({ ...veh, odometer: Number(e.target.value) })} /></Field><Field label="Notes"><input className="input" value={veh.notes ?? ''} onChange={(e) => setVeh({ ...veh, notes: e.target.value })} /></Field></div>}
      </Modal>
    </>
  )
}
