import { useState } from 'react'
import { Plus, Check, X, PackageOpen, Trash2 } from 'lucide-react'
import { useStore, useCurrentUser } from '@/store/useStore'
import { Card, PageHeader, Stat, Modal, Field, Alert } from '@/components/ui'
import { RELEASE_STATUS_LABEL, RELEASE_STATUS_TONE, canDecideTwoStep, stockBalance } from '@/lib/supply'
import { fmtDate, fmtDateTime, cx } from '@/lib/format'
import { useSupplyContext, TwoStepTrail } from './shared'
import type { StockRelease, StockReleaseLine } from '@/types'

export default function StockRequests() {
  const user = useCurrentUser()!
  const { supplyManage, canIssue } = useSupplyContext()
  const { releases, warehouses, items, movements, projects, budgets, staff, createRelease, decideRelease, issueRelease } = useStore()
  const me = staff.find((s) => s.userId === user.id)
  const [filter, setFilter] = useState<'open' | 'mine' | 'all'>('open')
  const [nw, setNw] = useState<{ warehouseId: string; projectId: string; budgetLine: string; purpose: string; destination: string; neededBy: string; lines: StockReleaseLine[] } | null>(null)
  const [decide, setDecide] = useState<{ r: StockRelease; approve: boolean } | null>(null)
  const [note, setNote] = useState('')
  const [issue, setIssue] = useState<{ r: StockRelease; issued: Record<string, number>; carrier: string; driverName: string; vehiclePlate: string } | null>(null)
  const [msg, setMsg] = useState<{ tone: 'success' | 'danger'; text: string } | null>(null)
  const list = releases.filter((r) => filter === 'all' || (filter === 'mine' ? r.requesterId === user.id : ['pending_approval', 'approved'].includes(r.status))).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
  const forMe = releases.filter((r) => r.status === 'pending_approval' && canDecideTwoStep(r.approvals, user) && r.requesterId !== user.id)
  const toIssue = releases.filter((r) => r.status === 'approved' && canIssue(r.warehouseId))
  const budgetLines = (projectId: string) => { const p = projects.find((x) => x.id === projectId); const b = budgets.find((x) => x.id === p?.budgetId); return b?.lines ?? [] }
  return (
    <>
      <PageHeader title="Stock release requests" subtitle="Form to take items out of a warehouse: the requester (RHS number) states the purpose, destination and project; the line manager then the Supply Chain Manager approve; the warehouse issues the goods on a waybill."
        actions={<button className="btn-primary" data-testid="new-release" onClick={() => setNw({ warehouseId: warehouses[0]?.id ?? '', projectId: '', budgetLine: '', purpose: '', destination: '', neededBy: '', lines: [] })}><Plus size={15} /> Request items</button>} />
      <div className="mb-5 grid gap-4 sm:grid-cols-4"><Stat label="Awaiting your approval" value={forMe.length} tone={forMe.length ? 'sun' : 'default'} /><Stat label="Approved — to issue" value={releases.filter((r) => r.status === 'approved').length} hint={toIssue.length ? `${toIssue.length} in your warehouses` : undefined} tone={toIssue.length ? 'brand' : 'default'} /><Stat label="Issued this month" value={releases.filter((r) => r.status === 'issued' && r.issuedAt?.startsWith(new Date().toISOString().slice(0, 7))).length} /><Stat label="My requests" value={releases.filter((r) => r.requesterId === user.id).length} /></div>
      {msg && <div className="mb-4"><Alert tone={msg.tone}>{msg.text}</Alert></div>}
      <div className="mb-3 flex gap-1">{(['open', 'mine', 'all'] as const).map((f) => <button key={f} onClick={() => setFilter(f)} className={cx('rounded-pill px-3 py-1 text-[12.5px] font-medium', filter === f ? 'bg-ink-900 text-white' : 'bg-surface text-ink-600 ring-1 ring-inset ring-line')}>{f === 'open' ? 'Open' : f === 'mine' ? 'My requests' : 'All'}</button>)}</div>
      <Card padded={false}><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-[13px]">
        <thead><tr><th className="table-th">Request</th><th className="table-th">Requester</th><th className="table-th">Warehouse → destination</th><th className="table-th">Items</th><th className="table-th">Project · line</th><th className="table-th">Approvals</th><th className="table-th">Status</th><th className="table-th w-44" /></tr></thead>
        <tbody>{list.length === 0 && <tr><td colSpan={8} className="table-td text-ink-500">Nothing here.</td></tr>}{list.map((r) => { const wh = warehouses.find((w) => w.id === r.warehouseId); return (
          <tr key={r.id} className="hover:bg-surface-muted"><td className="table-td"><span className="font-mono text-[12px]">{r.number}</span><div className="text-[12px] text-ink-600">{r.purpose}</div><div className="text-[11px] text-ink-400">{fmtDateTime(r.createdAt)} · needed {fmtDate(r.neededBy)}</div></td><td className="table-td"><div className="font-medium text-ink-900">{r.requesterName}</div><div className="font-mono text-[11.5px] text-ink-500">{r.rhsNumber}</div></td><td className="table-td text-[12.5px]"><b>{wh?.code}</b> {wh?.name}<div className="text-ink-500">→ {r.destination}</div></td><td className="table-td text-[12.5px]">{r.lines.map((l) => <div key={l.itemId}>{l.quantity} {l.unit} {l.description}{l.issued !== undefined && r.status === 'issued' && l.issued !== l.quantity && <span className="text-accent-700"> (issued {l.issued})</span>}</div>)}</td><td className="table-td text-[12.5px]">{r.projectCode ?? 'Core'}{r.budgetLine && <div className="font-mono text-[11px] text-ink-500">{r.budgetLine}</div>}</td><td className="table-td"><TwoStepTrail approvals={r.approvals} /></td><td className="table-td"><span className={cx('rounded-pill px-2 py-0.5 text-[11px] font-semibold', RELEASE_STATUS_TONE[r.status])}>{RELEASE_STATUS_LABEL[r.status]}</span>{r.waybillNumber && <div className="font-mono text-[11px] text-ink-500">{r.waybillNumber}</div>}</td>
            <td className="table-td"><div className="flex justify-end gap-1">{r.status === 'pending_approval' && canDecideTwoStep(r.approvals, user) && r.requesterId !== user.id && <><button className="btn-primary btn-sm" data-testid="rel-approve" onClick={() => { setNote(''); setDecide({ r, approve: true }) }}><Check size={13} /></button><button className="btn-danger-soft btn-sm" onClick={() => { setNote(''); setDecide({ r, approve: false }) }}><X size={13} /></button></>}{r.status === 'approved' && canIssue(r.warehouseId) && <button className="btn-primary btn-sm" data-testid="rel-issue" onClick={() => setIssue({ r, issued: Object.fromEntries(r.lines.map((l) => [l.itemId, l.quantity])), carrier: 'RHS fleet', driverName: '', vehiclePlate: '' })}><PackageOpen size={13} /> Issue</button>}</div></td></tr>) })}</tbody></table></div></Card>

      <Modal open={!!nw} onClose={() => setNw(null)} width="max-w-3xl" title="Stock release request" footer={<><button className="btn-secondary" onClick={() => setNw(null)}>Cancel</button><button className="btn-primary" data-testid="rel-submit" onClick={() => { if (!nw) return; const r = createRelease({ warehouseId: nw.warehouseId, projectId: nw.projectId || undefined, projectCode: projects.find((p) => p.id === nw.projectId)?.code, budgetLine: nw.budgetLine || undefined, purpose: nw.purpose, destination: nw.destination, neededBy: nw.neededBy, lines: nw.lines }); if (!r.ok) return alert(r.error); setMsg({ tone: 'success', text: `${r.release!.number} submitted for approval.` }); setNw(null) }}>Submit</button></>}>
        {nw && <div className="space-y-3 text-[13px]">
          <div className="rounded-control bg-surface-muted px-3 py-2 text-[12.5px] text-ink-700">Requested by <b>{user.name}</b> · RHS number <b className="font-mono">{me?.rhsNumber ?? '—'}</b></div>
          <div className="grid gap-3 sm:grid-cols-3"><Field label="From warehouse"><select className="input" value={nw.warehouseId} onChange={(e) => setNw({ ...nw, warehouseId: e.target.value, lines: [] })}>{warehouses.filter((w) => w.active).map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></Field><Field label="Project"><select className="input" value={nw.projectId} onChange={(e) => setNw({ ...nw, projectId: e.target.value, budgetLine: '' })}><option value="">Core / none</option>{projects.filter((p) => ['granted', 'active'].includes(p.stage)).map((p) => <option key={p.id} value={p.id}>{p.code} · {p.title.slice(0, 30)}</option>)}</select></Field><Field label="Budget line"><select className="input" value={nw.budgetLine} disabled={!nw.projectId} onChange={(e) => setNw({ ...nw, budgetLine: e.target.value })}><option value="">—</option>{budgetLines(nw.projectId).map((l) => <option key={l.id} value={l.code}>{l.code} · {l.description.slice(0, 30)}</option>)}</select></Field>
            <Field label="Purpose" required className="sm:col-span-2"><input className="input" data-testid="rel-purpose" value={nw.purpose} onChange={(e) => setNw({ ...nw, purpose: e.target.value })} placeholder="Fitting camp, distribution, office use…" /></Field><Field label="Needed by"><input type="date" className="input" value={nw.neededBy} onChange={(e) => setNw({ ...nw, neededBy: e.target.value })} /></Field><Field label="Destination" required className="sm:col-span-3"><input className="input" value={nw.destination} onChange={(e) => setNw({ ...nw, destination: e.target.value })} placeholder="Where the items go" /></Field></div>
          <div><div className="label">Items</div><table className="w-full"><thead><tr><th className="table-th">Item</th><th className="table-th text-right">In stock</th><th className="table-th w-28 text-right">Qty</th><th className="table-th w-8" /></tr></thead><tbody>{nw.lines.map((l, i) => <tr key={i}><td className="table-td">{l.description}</td><td className="table-td text-right">{stockBalance(movements, nw.warehouseId, l.itemId)} {l.unit}</td><td className="table-td py-1"><input type="number" min={1} className="input text-right" value={l.quantity} onChange={(e) => setNw({ ...nw, lines: nw.lines.map((x, j) => (j === i ? { ...x, quantity: Number(e.target.value) } : x)) })} /></td><td className="table-td"><button className="btn-ghost btn-sm text-accent-700" onClick={() => setNw({ ...nw, lines: nw.lines.filter((_, j) => j !== i) })}><Trash2 size={13} /></button></td></tr>)}</tbody></table>
            <select className="input mt-2" data-testid="rel-add-item" value="" onChange={(e) => { const it = items.find((i) => i.id === e.target.value); if (it && !nw.lines.some((l) => l.itemId === it.id)) setNw({ ...nw, lines: [...nw.lines, { itemId: it.id, description: it.description, unit: it.unit, quantity: 1 }] }) }}><option value="">+ add an item from this warehouse…</option>{items.filter((it) => stockBalance(movements, nw.warehouseId, it.id) > 0).map((it) => <option key={it.id} value={it.id}>{it.sku} · {it.description} ({stockBalance(movements, nw.warehouseId, it.id)} {it.unit})</option>)}</select></div>
        </div>}
      </Modal>
      <Modal open={!!decide} onClose={() => setDecide(null)} title={decide ? `${decide.approve ? 'Approve' : 'Reject'} ${decide.r.number}` : ''} footer={<><button className="btn-secondary" onClick={() => setDecide(null)}>Cancel</button><button className={decide?.approve ? 'btn-primary' : 'btn-danger'} data-testid="rel-confirm" onClick={() => { if (decide) decideRelease(decide.r.id, decide.approve, note || undefined); setDecide(null) }}>Confirm</button></>}>
        {decide && <div className="space-y-3 text-[13px]"><p className="text-ink-700"><b>{decide.r.requesterName}</b> ({decide.r.rhsNumber}) · {decide.r.purpose} → {decide.r.destination}</p><ul className="list-disc pl-5 text-ink-700">{decide.r.lines.map((l) => <li key={l.itemId}>{l.quantity} {l.unit} {l.description}</li>)}</ul><Field label="Note (optional)"><textarea className="input min-h-[56px]" value={note} onChange={(e) => setNote(e.target.value)} /></Field></div>}
      </Modal>
      <Modal open={!!issue} onClose={() => setIssue(null)} width="max-w-2xl" title={issue ? `Issue ${issue.r.number} from ${warehouses.find((w) => w.id === issue.r.warehouseId)?.code}` : ''} footer={<><button className="btn-secondary" onClick={() => setIssue(null)}>Cancel</button><button className="btn-primary" data-testid="rel-issue-confirm" onClick={() => { if (!issue) return; const r = issueRelease(issue.r.id, issue.issued, { carrier: issue.carrier, driverName: issue.driverName, vehiclePlate: issue.vehiclePlate }); if (!r.ok) return alert(r.error); setMsg({ tone: 'success', text: 'Stock issued — waybill created and the requester notified.' }); setIssue(null) }}><PackageOpen size={14} /> Issue & print waybill</button></>}>
        {issue && <div className="space-y-3 text-[13px]"><table className="w-full"><thead><tr><th className="table-th">Item</th><th className="table-th text-right">Requested</th><th className="table-th text-right">In stock</th><th className="table-th w-28 text-right">Issue</th></tr></thead><tbody>{issue.r.lines.map((l) => <tr key={l.itemId}><td className="table-td">{l.description}</td><td className="table-td text-right">{l.quantity}</td><td className="table-td text-right">{stockBalance(movements, issue.r.warehouseId, l.itemId)}</td><td className="table-td py-1"><input type="number" min={0} max={l.quantity} className="input text-right" value={issue.issued[l.itemId] ?? 0} onChange={(e) => setIssue({ ...issue, issued: { ...issue.issued, [l.itemId]: Number(e.target.value) } })} /></td></tr>)}</tbody></table><div className="grid gap-3 sm:grid-cols-3"><Field label="Carrier"><input className="input" value={issue.carrier} onChange={(e) => setIssue({ ...issue, carrier: e.target.value })} /></Field><Field label="Driver"><input className="input" value={issue.driverName} onChange={(e) => setIssue({ ...issue, driverName: e.target.value })} /></Field><Field label="Vehicle plate"><input className="input" value={issue.vehiclePlate} onChange={(e) => setIssue({ ...issue, vehiclePlate: e.target.value })} /></Field></div>{!supplyManage && <Alert tone="info">You are issuing as the warehouse manager.</Alert>}</div>}
      </Modal>
    </>
  )
}
