import { useState } from 'react'
import { Plus, Pencil, ArrowLeftRight, SlidersHorizontal, Download, Warehouse as WarehouseIcon, AlertTriangle } from 'lucide-react'
import { useStore } from '@/store/useStore'
import { Card, PageHeader, Stat, Modal, Field, Alert, Tabs } from '@/components/ui'
import { balancesFor, avgCost, MOVEMENT_LABEL } from '@/lib/supply'
import { fmtMoney, fmtDateTime, cx } from '@/lib/format'
import { useSupplyContext } from './shared'
import type { Warehouse, StockItem } from '@/types'

type Tab = 'stock' | 'warehouses' | 'movements' | 'items'

export default function Warehouses() {
  const { supplyManage, canIssue } = useSupplyContext()
  const { warehouses, items, movements, staff, settings, country, upsertWarehouse, upsertItem, adjustStock, transferStock } = useStore()
  const [tab, setTab] = useState<Tab>('stock')
  const visible = warehouses.filter((w) => country === 'all' || w.country === country)
  const [whId, setWhId] = useState(visible[0]?.id ?? '')
  const [editWh, setEditWh] = useState<Partial<Warehouse> | null>(null)
  const [editItem, setEditItem] = useState<Partial<StockItem> | null>(null)
  const [adj, setAdj] = useState<{ itemId: string; quantity: number; note: string; unitCost: number } | null>(null)
  const [xfer, setXfer] = useState<{ toId: string; lines: Record<string, number>; carrier: string; driverName: string; vehiclePlate: string; projectCode: string } | null>(null)
  const [msg, setMsg] = useState<{ tone: 'success' | 'danger'; text: string } | null>(null)
  const bal = balancesFor(movements, warehouses)
  const cur = bal.find((b) => b.warehouse.id === whId)
  const rows = items.map((it) => ({ it, qty: cur?.items[it.id] ?? 0, cost: avgCost(movements, it.id) })).filter((r) => r.qty !== 0 || tab === 'items')
  const totalValue = bal.filter((b) => visible.some((w) => w.id === b.warehouse.id)).reduce((s, b) => s + Object.entries(b.items).reduce((t, [id, q]) => t + q * avgCost(movements, id), 0), 0)
  const low = bal.flatMap((b) => Object.entries(b.items).filter(([id, q]) => { const it = items.find((i) => i.id === id); return it?.minLevel && q < it.minLevel && q > 0 }).map(([id]) => ({ w: b.warehouse, it: items.find((i) => i.id === id)! })))
  const exportX = async () => { const X = await import('xlsx'); const wb = X.utils.book_new(); X.utils.book_append_sheet(wb, X.utils.aoa_to_sheet([['Warehouse', 'Country', 'SKU', 'Item', 'Category', 'Unit', 'Balance', 'Min level', 'Avg cost', 'Value'], ...bal.flatMap((b) => Object.entries(b.items).map(([id, q]) => { const it = items.find((i) => i.id === id)!; return [b.warehouse.code, b.warehouse.country, it.sku, it.description, it.category, it.unit, q, it.minLevel ?? '', Math.round(avgCost(movements, id) * 100) / 100, Math.round(q * avgCost(movements, id) * 100) / 100] }))]), 'Stock'); X.utils.book_append_sheet(wb, X.utils.aoa_to_sheet([['Date', 'Movement', 'Type', 'Warehouse', 'Item', 'Qty', 'Unit cost', 'Reference', 'Project', 'By', 'Note'], ...movements.map((m) => [m.at.slice(0, 16).replace('T', ' '), m.number, MOVEMENT_LABEL[m.type], warehouses.find((w) => w.id === m.warehouseId)?.code, items.find((i) => i.id === m.itemId)?.description, m.quantity, m.unitCost ?? '', m.refNumber ?? '', m.projectCode ?? '', m.byName, m.note ?? ''])]), 'Movements'); X.writeFile(wb, 'RHS_Stock.xlsx') }
  return (
    <>
      <PageHeader title="Warehouses & stock" subtitle="Stock per warehouse in every country: receipts from GRNs, issues against approved release requests, transfers on waybills, adjustments. Balances are the sum of the movement ledger."
        actions={<div className="flex gap-2"><button className="btn-secondary" onClick={exportX}><Download size={15} /> Export</button>{supplyManage && <button className="btn-primary" onClick={() => setEditWh({ country: settings.countries[0], active: true })}><Plus size={15} /> Warehouse</button>}</div>} />
      <div className="mb-5 grid gap-4 sm:grid-cols-4"><Stat label="Warehouses" value={visible.length} hint={[...new Set(visible.map((w) => w.country))].join(' · ')} tone="brand" /><Stat label="Stock value (avg cost)" value={fmtMoney(totalValue, settings.defaultCurrency)} /><Stat label="Catalogue items" value={items.length} /><Stat label="Below minimum level" value={low.length} hint={low.slice(0, 3).map((l) => `${l.it.sku} @ ${l.w.code}`).join(' · ') || undefined} tone={low.length ? 'accent' : 'default'} /></div>
      {msg && <div className="mb-4"><Alert tone={msg.tone}>{msg.text}</Alert></div>}
      <Tabs tabs={[{ id: 'stock', label: 'Stock balances' }, { id: 'warehouses', label: 'Warehouses', count: visible.length }, { id: 'movements', label: 'Movement ledger', count: movements.length }, { id: 'items', label: 'Item catalogue' }]} value={tab} onChange={setTab} />
      {tab === 'stock' && (
        <div className="mt-5">
          <div className="mb-3 flex flex-wrap items-center gap-2"><select className="input w-80" value={whId} onChange={(e) => setWhId(e.target.value)}>{visible.map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name} ({w.country})</option>)}</select>{cur && canIssue(cur.warehouse.id) && <><button className="btn-secondary btn-sm" onClick={() => setXfer({ toId: warehouses.find((w) => w.id !== whId)?.id ?? '', lines: {}, carrier: 'RHS fleet', driverName: '', vehiclePlate: '', projectCode: '' })}><ArrowLeftRight size={13} /> Transfer to another warehouse</button></>}</div>
          <Card padded={false}><table className="w-full text-[13px]"><thead><tr><th className="table-th">SKU</th><th className="table-th">Item</th><th className="table-th">Category</th><th className="table-th text-right">Balance</th><th className="table-th text-right">Min</th><th className="table-th text-right">Avg cost</th><th className="table-th text-right">Value</th><th className="table-th w-28" /></tr></thead>
            <tbody>{rows.length === 0 && <tr><td colSpan={8} className="table-td text-ink-500">No stock in this warehouse.</td></tr>}{rows.map(({ it, qty, cost }) => <tr key={it.id} className="hover:bg-surface-muted"><td className="table-td font-mono text-[12px]">{it.sku}</td><td className="table-td font-medium text-ink-900">{it.description}</td><td className="table-td text-ink-600">{it.category}</td><td className={cx('table-td text-right font-semibold tabular-nums', !!it.minLevel && qty < it.minLevel && 'text-accent-700')}>{qty} {it.unit}{it.minLevel && qty < it.minLevel && <AlertTriangle size={12} className="ml-1 inline" />}</td><td className="table-td text-right text-ink-500">{it.minLevel ?? '—'}</td><td className="table-td text-right tabular-nums">{cost ? fmtMoney(cost, settings.defaultCurrency) : '—'}</td><td className="table-td text-right tabular-nums">{fmtMoney(qty * cost, settings.defaultCurrency)}</td><td className="table-td">{cur && canIssue(cur.warehouse.id) && <button className="btn-ghost btn-sm" onClick={() => setAdj({ itemId: it.id, quantity: 0, note: '', unitCost: cost })}><SlidersHorizontal size={13} /> Adjust</button>}</td></tr>)}</tbody></table></Card>
        </div>
      )}
      {tab === 'warehouses' && <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((w) => { const b = bal.find((x) => x.warehouse.id === w.id)!; const lines = Object.values(b.items).filter((q) => q > 0).length; const mgr = staff.find((s) => s.id === w.managerStaffId); return <Card key={w.id} title={<span className="flex items-center gap-2"><WarehouseIcon size={16} /> {w.name}</span>} description={`${w.code} · ${w.country}`} actions={supplyManage && <button className="btn-ghost btn-sm" onClick={() => setEditWh(w)}><Pencil size={13} /></button>}><div className="text-[13px] text-ink-700">{w.address}</div><div className="mt-2 text-[12.5px] text-ink-600">Manager: <b className="text-ink-900">{mgr ? `${mgr.name} (${mgr.rhsNumber})` : '—'}</b></div><div className="mt-2 flex gap-4 text-[12.5px]"><span><b className="text-[16px] text-ink-900">{lines}</b> items in stock</span><span><b className="text-[16px] text-ink-900">{fmtMoney(Object.entries(b.items).reduce((t, [id, q]) => t + q * avgCost(movements, id), 0), settings.defaultCurrency)}</b> value</span></div>{!w.active && <div className="mt-2 text-[12px] text-accent-700">Inactive</div>}</Card> })}</div>}
      {tab === 'movements' && <Card className="mt-5" padded={false}><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-[13px]"><thead><tr><th className="table-th">Date</th><th className="table-th">Movement</th><th className="table-th">Type</th><th className="table-th">Warehouse</th><th className="table-th">Item</th><th className="table-th text-right">Qty</th><th className="table-th">Reference</th><th className="table-th">Project</th><th className="table-th">By</th></tr></thead><tbody>{[...movements].sort((a, b) => b.at.localeCompare(a.at)).slice(0, 200).map((m) => <tr key={m.id} className="hover:bg-surface-muted"><td className="table-td text-[12px] text-ink-600">{fmtDateTime(m.at)}</td><td className="table-td font-mono text-[12px]">{m.number}</td><td className="table-td">{MOVEMENT_LABEL[m.type]}</td><td className="table-td">{warehouses.find((w) => w.id === m.warehouseId)?.code}</td><td className="table-td">{items.find((i) => i.id === m.itemId)?.description}</td><td className={cx('table-td text-right font-semibold tabular-nums', m.quantity < 0 ? 'text-accent-700' : 'text-brand-800')}>{m.quantity > 0 ? '+' : ''}{m.quantity}</td><td className="table-td font-mono text-[12px]">{m.refNumber ?? '—'}</td><td className="table-td text-[12px]">{m.projectCode ?? '—'}</td><td className="table-td text-[12px] text-ink-600">{m.byName}{m.note && <div className="text-ink-500">{m.note}</div>}</td></tr>)}</tbody></table></div></Card>}
      {tab === 'items' && <Card className="mt-5" padded={false} actions={supplyManage && <button className="btn-primary btn-sm" onClick={() => setEditItem({ unit: 'pcs', category: 'General' })}><Plus size={13} /> Item</button>} title="Catalogue"><table className="w-full text-[13px]"><thead><tr><th className="table-th">SKU</th><th className="table-th">Item</th><th className="table-th">Category</th><th className="table-th">Unit</th><th className="table-th text-right">Min level</th><th className="table-th text-right">Total on hand</th><th className="table-th w-12" /></tr></thead><tbody>{items.map((it) => <tr key={it.id} className="hover:bg-surface-muted"><td className="table-td font-mono text-[12px]">{it.sku}</td><td className="table-td font-medium text-ink-900">{it.description}</td><td className="table-td text-ink-600">{it.category}</td><td className="table-td">{it.unit}</td><td className="table-td text-right">{it.minLevel ?? '—'}</td><td className="table-td text-right font-semibold">{bal.reduce((s, b) => s + (b.items[it.id] ?? 0), 0)}</td><td className="table-td">{supplyManage && <button className="btn-ghost btn-sm" onClick={() => setEditItem(it)}><Pencil size={13} /></button>}</td></tr>)}</tbody></table></Card>}

      <Modal open={!!editWh} onClose={() => setEditWh(null)} title={editWh?.id ? 'Edit warehouse' : 'New warehouse'} footer={<><button className="btn-secondary" onClick={() => setEditWh(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!editWh?.name?.trim()) return alert('Name is required.'); upsertWarehouse({ ...editWh, name: editWh.name.trim(), country: editWh.country! }); setEditWh(null) }}>Save</button></>}>
        {editWh && <div className="grid gap-3 sm:grid-cols-2"><Field label="Name" required className="sm:col-span-2"><input className="input" value={editWh.name ?? ''} onChange={(e) => setEditWh({ ...editWh, name: e.target.value })} /></Field><Field label="Country"><select className="input" value={editWh.country} onChange={(e) => setEditWh({ ...editWh, country: e.target.value })}>{settings.countries.map((c) => <option key={c}>{c}</option>)}</select></Field><Field label="Code" hint="auto if blank"><input className="input font-mono" value={editWh.code ?? ''} onChange={(e) => setEditWh({ ...editWh, code: e.target.value })} /></Field><Field label="Address" className="sm:col-span-2"><input className="input" value={editWh.address ?? ''} onChange={(e) => setEditWh({ ...editWh, address: e.target.value })} /></Field><Field label="Warehouse manager (staff)"><select className="input" value={editWh.managerStaffId ?? ''} onChange={(e) => setEditWh({ ...editWh, managerStaffId: e.target.value || undefined })}><option value="">—</option>{staff.filter((s) => s.status === 'active').map((s) => <option key={s.id} value={s.id}>{s.rhsNumber} · {s.name}</option>)}</select></Field><label className="flex items-center gap-2 self-end text-[13px]"><input type="checkbox" checked={editWh.active ?? true} onChange={(e) => setEditWh({ ...editWh, active: e.target.checked })} /> Active</label></div>}
      </Modal>
      <Modal open={!!editItem} onClose={() => setEditItem(null)} title={editItem?.id ? 'Edit item' : 'New catalogue item'} footer={<><button className="btn-secondary" onClick={() => setEditItem(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!editItem?.description?.trim()) return alert('Description is required.'); upsertItem({ ...editItem, description: editItem.description.trim() }); setEditItem(null) }}>Save</button></>}>
        {editItem && <div className="grid gap-3 sm:grid-cols-2"><Field label="Description" required className="sm:col-span-2"><input className="input" value={editItem.description ?? ''} onChange={(e) => setEditItem({ ...editItem, description: e.target.value })} /></Field><Field label="SKU" hint="auto if blank"><input className="input font-mono" value={editItem.sku ?? ''} onChange={(e) => setEditItem({ ...editItem, sku: e.target.value })} /></Field><Field label="Category"><input className="input" value={editItem.category ?? ''} onChange={(e) => setEditItem({ ...editItem, category: e.target.value })} /></Field><Field label="Unit"><input className="input" value={editItem.unit ?? ''} onChange={(e) => setEditItem({ ...editItem, unit: e.target.value })} /></Field><Field label="Minimum level"><input type="number" className="input" value={editItem.minLevel ?? ''} onChange={(e) => setEditItem({ ...editItem, minLevel: e.target.value === '' ? undefined : Number(e.target.value) })} /></Field></div>}
      </Modal>
      <Modal open={!!adj} onClose={() => setAdj(null)} title={adj ? `Adjust ${items.find((i) => i.id === adj.itemId)?.description}` : ''} footer={<><button className="btn-secondary" onClick={() => setAdj(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!adj) return; const r = adjustStock(whId, adj.itemId, adj.quantity, adj.note, adj.quantity > 0 ? adj.unitCost : undefined); if (!r.ok) return alert(r.error); setMsg({ tone: 'success', text: 'Stock adjusted.' }); setAdj(null) }}>Post</button></>}>
        {adj && <div className="grid gap-3 sm:grid-cols-2"><Field label="Quantity (+ receipt / − write-off)" required><input type="number" className="input" value={adj.quantity} onChange={(e) => setAdj({ ...adj, quantity: Number(e.target.value) })} /></Field>{adj.quantity > 0 && <Field label="Unit cost"><input type="number" className="input" value={adj.unitCost} onChange={(e) => setAdj({ ...adj, unitCost: Number(e.target.value) })} /></Field>}<Field label="Reason" required className="sm:col-span-2"><input className="input" value={adj.note} onChange={(e) => setAdj({ ...adj, note: e.target.value })} placeholder="Physical count difference, damage, donation in kind…" /></Field></div>}
      </Modal>
      <Modal open={!!xfer} onClose={() => setXfer(null)} width="max-w-2xl" title={`Transfer from ${cur?.warehouse.code}`} footer={<><button className="btn-secondary" onClick={() => setXfer(null)}>Cancel</button><button className="btn-primary" data-testid="xfer-dispatch" onClick={() => { if (!xfer) return; const r = transferStock(whId, xfer.toId, Object.entries(xfer.lines).map(([itemId, quantity]) => ({ itemId, quantity })), { carrier: xfer.carrier, driverName: xfer.driverName, vehiclePlate: xfer.vehiclePlate, projectCode: xfer.projectCode || undefined }); if (!r.ok) return alert(r.error); setMsg({ tone: 'success', text: `Transfer dispatched on waybill ${r.waybill!.number} — the receiving warehouse confirms on the Waybills page.` }); setXfer(null) }}>Dispatch with waybill</button></>}>
        {xfer && <div className="space-y-3 text-[13px]"><Field label="To warehouse"><select className="input" value={xfer.toId} onChange={(e) => setXfer({ ...xfer, toId: e.target.value })}>{warehouses.filter((w) => w.id !== whId && w.active).map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name} ({w.country})</option>)}</select></Field>
          <table className="w-full"><thead><tr><th className="table-th">Item</th><th className="table-th text-right">Available</th><th className="table-th w-32 text-right">Transfer</th></tr></thead><tbody>{rows.filter((r) => r.qty > 0).map(({ it, qty }) => <tr key={it.id}><td className="table-td">{it.description}</td><td className="table-td text-right">{qty} {it.unit}</td><td className="table-td py-1"><input type="number" min={0} max={qty} className="input text-right" value={xfer.lines[it.id] ?? ''} onChange={(e) => setXfer({ ...xfer, lines: { ...xfer.lines, [it.id]: Number(e.target.value) } })} /></td></tr>)}</tbody></table>
          <div className="grid gap-3 sm:grid-cols-4"><Field label="Carrier"><input className="input" value={xfer.carrier} onChange={(e) => setXfer({ ...xfer, carrier: e.target.value })} /></Field><Field label="Driver"><input className="input" value={xfer.driverName} onChange={(e) => setXfer({ ...xfer, driverName: e.target.value })} /></Field><Field label="Vehicle plate"><input className="input" value={xfer.vehiclePlate} onChange={(e) => setXfer({ ...xfer, vehiclePlate: e.target.value })} /></Field><Field label="Project (optional)"><input className="input" value={xfer.projectCode} onChange={(e) => setXfer({ ...xfer, projectCode: e.target.value })} placeholder="GR-2025-IRB-03" /></Field></div></div>}
      </Modal>
    </>
  )
}
