import { useState } from 'react'
import { Plus, Printer, CheckCircle2, Trash2 } from 'lucide-react'
import { useStore } from '@/store/useStore'
import { Card, PageHeader, Stat, Modal, Field, KV } from '@/components/ui'
import { WAYBILL_STATUS_TONE } from '@/lib/supply'
import { fmtDate, fmtDateTime, cx } from '@/lib/format'
import { useSupplyContext } from './shared'
import type { Waybill, WaybillLine } from '@/types'

export default function Waybills() {
  const { supplyManage } = useSupplyContext()
  const { waybills, settings, createWaybill, receiveWaybill } = useStore()
  const [view, setView] = useState<Waybill | null>(null)
  const [nw, setNw] = useState<{ kind: Waybill['kind']; from: string; to: string; date: string; carrier: string; driverName: string; vehiclePlate: string; projectCode: string; notes: string; lines: WaybillLine[] } | null>(null)
  const list = [...waybills].sort((a, b) => b.dispatchedAt.localeCompare(a.dispatchedAt))
  const print = () => window.print()
  return (
    <>
      <PageHeader title="Waybills" subtitle="Every movement of goods leaves a waybill: inbound from suppliers (with the GRN), transfers between warehouses, and outbound issues against release requests. The receiving side confirms receipt."
        actions={supplyManage && <button className="btn-primary" onClick={() => setNw({ kind: 'outbound', from: '', to: '', date: new Date().toISOString().slice(0, 10), carrier: 'RHS fleet', driverName: '', vehiclePlate: '', projectCode: '', notes: '', lines: [{ description: '', quantity: 1, unit: 'pcs' }] })}><Plus size={15} /> Manual waybill</button>} />
      <div className="mb-5 grid gap-4 sm:grid-cols-3"><Stat label="In transit" value={waybills.filter((w) => w.status === 'dispatched').length} tone={waybills.some((w) => w.status === 'dispatched') ? 'sun' : 'default'} /><Stat label="Received" value={waybills.filter((w) => w.status === 'received').length} tone="brand" /><Stat label="This month" value={waybills.filter((w) => w.dispatchedAt.startsWith(new Date().toISOString().slice(0, 7))).length} /></div>
      <Card padded={false}><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-[13px]"><thead><tr><th className="table-th">Waybill</th><th className="table-th">Kind</th><th className="table-th">From → to</th><th className="table-th">Items</th><th className="table-th">Transport</th><th className="table-th">Reference</th><th className="table-th">Status</th><th className="table-th w-36" /></tr></thead>
        <tbody>{list.map((w) => <tr key={w.id} className="hover:bg-surface-muted"><td className="table-td"><button className="font-mono text-[12px] font-semibold text-brand-700 hover:underline" onClick={() => setView(w)}>{w.number}</button><div className="text-[11px] text-ink-500">{fmtDate(w.date)} · {w.dispatchedByName}</div></td><td className="table-td capitalize">{w.kind}</td><td className="table-td text-[12.5px]">{w.from}<div className="text-ink-500">→ {w.to}</div></td><td className="table-td text-[12.5px]">{w.lines.slice(0, 3).map((l, i) => <div key={i}>{l.quantity} {l.unit} {l.description}</div>)}{w.lines.length > 3 && <div className="text-ink-400">+{w.lines.length - 3} more</div>}</td><td className="table-td text-[12px] text-ink-600">{w.carrier}{w.driverName && ` · ${w.driverName}`}{w.vehiclePlate && ` · ${w.vehiclePlate}`}</td><td className="table-td font-mono text-[11.5px]">{w.refNumber ?? '—'}{w.projectCode && <div className="text-ink-500">{w.projectCode}</div>}</td><td className="table-td"><span className={cx('rounded-pill px-2 py-0.5 text-[11px] font-semibold capitalize', WAYBILL_STATUS_TONE[w.status])}>{w.status}</span>{w.receivedAt && <div className="text-[11px] text-ink-500">{w.receivedByName} · {fmtDate(w.receivedAt)}</div>}</td><td className="table-td"><div className="flex justify-end gap-1">{w.status === 'dispatched' && <button className="btn-primary btn-sm" data-testid="wb-receive" onClick={() => { if (confirm(`Confirm receipt of ${w.number} at ${w.to}?`)) receiveWaybill(w.id) }}><CheckCircle2 size={13} /> Received</button>}<button className="btn-ghost btn-sm" onClick={() => setView(w)}><Printer size={13} /></button></div></td></tr>)}</tbody></table></div></Card>

      <Modal open={!!view} onClose={() => setView(null)} width="max-w-2xl" title={view ? `Waybill ${view.number}` : ''} footer={<><button className="btn-secondary" onClick={print}><Printer size={14} /> Print</button>{view?.status === 'dispatched' && <button className="btn-primary" onClick={() => { receiveWaybill(view.id); setView(null) }}><CheckCircle2 size={14} /> Confirm receipt</button>}<button className="btn-secondary" onClick={() => setView(null)}>Close</button></>}>
        {view && <div className="text-[13px]"><div className="mb-3 flex items-start justify-between"><div><div className="text-[16px] font-bold text-ink-900">{settings.orgName}</div><div className="text-ink-500">{settings.address}</div></div><div className="text-right"><div className="text-[18px] font-bold">WAYBILL</div><div className="font-mono">{view.number}</div><div className="text-ink-500 capitalize">{view.kind} · {fmtDate(view.date)}</div></div></div>
          <div className="grid gap-x-6 sm:grid-cols-2"><KV k="From" v={view.from} /><KV k="To" v={view.to} /><KV k="Carrier" v={view.carrier || '—'} /><KV k="Driver · vehicle" v={`${view.driverName || '—'} · ${view.vehiclePlate || '—'}`} /><KV k="Reference" v={view.refNumber ?? '—'} /><KV k="Project" v={view.projectCode ?? '—'} /></div>
          <table className="my-3 w-full"><thead><tr><th className="table-th w-8">#</th><th className="table-th">Description</th><th className="table-th text-right">Qty</th><th className="table-th">Unit</th></tr></thead><tbody>{view.lines.map((l, i) => <tr key={i}><td className="table-td">{i + 1}</td><td className="table-td">{l.description}{l.assetId && <span className="ml-1 font-mono text-[11px] text-ink-500">asset</span>}</td><td className="table-td text-right">{l.quantity}</td><td className="table-td">{l.unit}</td></tr>)}</tbody></table>
          {view.notes && <div className="mb-3 text-ink-700">{view.notes}</div>}
          <div className="grid gap-4 sm:grid-cols-2 text-[12.5px]"><div className="rounded-control border border-line p-3"><div className="label">Dispatched by</div>{view.dispatchedByName}<div className="text-ink-500">{fmtDateTime(view.dispatchedAt)}</div></div><div className="rounded-control border border-line p-3"><div className="label">Received by</div>{view.receivedByName ?? <span className="text-ink-400">pending</span>}{view.receivedAt && <div className="text-ink-500">{fmtDateTime(view.receivedAt)}</div>}</div></div>
          <div className="mt-3 text-[11px] text-ink-400">Document owner: Bilal Abbassi · {settings.orgName}</div></div>}
      </Modal>
      <Modal open={!!nw} onClose={() => setNw(null)} width="max-w-2xl" title="Manual waybill" footer={<><button className="btn-secondary" onClick={() => setNw(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!nw || !nw.from.trim() || !nw.to.trim()) return alert('From and to are required.'); createWaybill({ ...nw, projectCode: nw.projectCode || undefined, lines: nw.lines.filter((l) => l.description.trim()) }); setNw(null) }}>Issue waybill</button></>}>
        {nw && <div className="space-y-3 text-[13px]"><div className="grid gap-3 sm:grid-cols-3"><Field label="Kind"><select className="input" value={nw.kind} onChange={(e) => setNw({ ...nw, kind: e.target.value as Waybill['kind'] })}><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="transfer">Transfer</option></select></Field><Field label="Date"><input type="date" className="input" value={nw.date} onChange={(e) => setNw({ ...nw, date: e.target.value })} /></Field><Field label="Project"><input className="input" value={nw.projectCode} onChange={(e) => setNw({ ...nw, projectCode: e.target.value })} /></Field><Field label="From" required><input className="input" value={nw.from} onChange={(e) => setNw({ ...nw, from: e.target.value })} /></Field><Field label="To" required className="sm:col-span-2"><input className="input" value={nw.to} onChange={(e) => setNw({ ...nw, to: e.target.value })} /></Field><Field label="Carrier"><input className="input" value={nw.carrier} onChange={(e) => setNw({ ...nw, carrier: e.target.value })} /></Field><Field label="Driver"><input className="input" value={nw.driverName} onChange={(e) => setNw({ ...nw, driverName: e.target.value })} /></Field><Field label="Vehicle plate"><input className="input" value={nw.vehiclePlate} onChange={(e) => setNw({ ...nw, vehiclePlate: e.target.value })} /></Field></div>
          <div><div className="label">Lines</div>{nw.lines.map((l, i) => <div key={i} className="mb-1 grid grid-cols-[1fr_90px_80px_32px] gap-2"><input className="input" placeholder="Description" value={l.description} onChange={(e) => setNw({ ...nw, lines: nw.lines.map((x, j) => (j === i ? { ...x, description: e.target.value } : x)) })} /><input type="number" className="input" value={l.quantity} onChange={(e) => setNw({ ...nw, lines: nw.lines.map((x, j) => (j === i ? { ...x, quantity: Number(e.target.value) } : x)) })} /><input className="input" value={l.unit} onChange={(e) => setNw({ ...nw, lines: nw.lines.map((x, j) => (j === i ? { ...x, unit: e.target.value } : x)) })} /><button className="btn-ghost btn-sm text-accent-700" onClick={() => setNw({ ...nw, lines: nw.lines.filter((_, j) => j !== i) })}><Trash2 size={13} /></button></div>)}<button className="btn-secondary btn-sm" onClick={() => setNw({ ...nw, lines: [...nw.lines, { description: '', quantity: 1, unit: 'pcs' }] })}><Plus size={13} /> Line</button></div>
          <Field label="Notes"><input className="input" value={nw.notes} onChange={(e) => setNw({ ...nw, notes: e.target.value })} /></Field></div>}
      </Modal>
    </>
  )
}
