import { useState } from 'react'
import { Save } from 'lucide-react'
import { useStore } from '@/store/useStore'
import { Card, PageHeader, Field, Alert } from '@/components/ui'
import { Logo } from '@/components/Logo'
import type { OrgSettings } from '@/types'

export default function Settings() {
  const { settings, updateSettings } = useStore()
  const [s, setS] = useState<OrgSettings>(settings)
  const [saved, setSaved] = useState(false)
  const set = (p: Partial<OrgSettings>) => setS((x) => ({ ...x, ...p }))
  return (
    <>
      <PageHeader title="Settings" subtitle="Organisation identity, procurement policy thresholds and document defaults."
        actions={<button className="btn-primary" onClick={() => { updateSettings(s); setSaved(true); setTimeout(() => setSaved(false), 2000) }}><Save size={15} /> Save</button>} />
      {saved && <div className="mb-4"><Alert tone="success">Settings saved.</Alert></div>}
      <div className="grid gap-6 xl:grid-cols-3">
        <div className="space-y-6 xl:col-span-2">
          <Card title="Organisation">
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Organisation name"><input className="input" value={s.orgName} onChange={(e) => set({ orgName: e.target.value })} /></Field>
              <Field label="Short name"><input className="input" value={s.orgShort} onChange={(e) => set({ orgShort: e.target.value })} /></Field>
              <Field label="Tagline" className="sm:col-span-2"><input className="input" value={s.tagline} onChange={(e) => set({ tagline: e.target.value })} /></Field>
              <Field label="Address" className="sm:col-span-2"><input className="input" value={s.address} onChange={(e) => set({ address: e.target.value })} /></Field>
              <Field label="Email"><input className="input" value={s.email} onChange={(e) => set({ email: e.target.value })} /></Field>
              <Field label="Phone"><input className="input" value={s.phone} onChange={(e) => set({ phone: e.target.value })} /></Field>
              <Field label="Website"><input className="input" value={s.website} onChange={(e) => set({ website: e.target.value })} /></Field>
            </div>
          </Card>
          <Card title="Procurement policy">
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Required number of quotations"><input type="number" min={1} className="input" value={s.quotationMinimum} onChange={(e) => set({ quotationMinimum: Number(e.target.value) })} /></Field>
              <Field label="Quotation threshold" hint="Requisitions at or above this value require the full quotation set"><input type="number" className="input" value={s.quotationThreshold} onChange={(e) => set({ quotationThreshold: Number(e.target.value) })} /></Field>
              <Field label="Default currency"><select className="input" value={s.defaultCurrency} onChange={(e) => set({ defaultCurrency: e.target.value as OrgSettings['defaultCurrency'] })}><option>JOD</option><option>USD</option><option>EUR</option></select></Field>
              <Field label="Invoice price tolerance %" hint="Unit-price variance vs PO allowed by the 3-way match"><input type="number" step="0.5" className="input" value={s.priceTolerancePct} onChange={(e) => set({ priceTolerancePct: Number(e.target.value) })} /></Field>
              <Field label="Default payment terms (days)"><input type="number" className="input" value={s.paymentTermsDays} onChange={(e) => set({ paymentTermsDays: Number(e.target.value) })} /></Field>
              <Field label="Default tax rate %"><input type="number" className="input" value={s.taxRate} onChange={(e) => set({ taxRate: Number(e.target.value) })} /></Field>
            </div>
          </Card>
        </div>
        <div className="space-y-6">
          <Card title="Brand preview" description="From RHS Brand Guideline 2025">
            <div className="rounded-card border border-line p-4"><Logo /></div>
            <div className="mt-3 rounded-card bg-brand-600 p-4"><Logo inverse /></div>
            <div className="mt-4 grid grid-cols-5 gap-1.5">
              {[['bg-brand-600', '#00853f'], ['bg-accent-600', '#d21e47'], ['bg-sun-500', '#ffb32c'], ['bg-ink-900', '#152b38'], ['bg-black', '#000000']].map(([c, h]) => <div key={h}><div className={`h-10 rounded-control ${c}`} /><div className="mt-1 text-center font-mono text-[10px] text-ink-500">{h}</div></div>)}
            </div>
            <div className="mt-3 text-[12px] text-ink-500">Typeface: Helvetica Neue · Secondary: Myriad Pro · Arabic: Helvetica Neue W23</div>
          </Card>
          <Card title="Document ownership"><p className="text-[13px] text-ink-700">All documents generated by this system are owned and created by <b>Bilal Abbassi</b> on behalf of {s.orgName}.</p></Card>
        </div>
      </div>
    </>
  )
}
